package cli

import "io"

const fishCompletions = `# Fish completions for yati
# Generated by: yati completion fish

function __yati_subcommand_is
    set -l cmd (commandline -opc)
    contains -- $argv[1] $cmd[2..]
end

function __yati_needs_subcommand
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __yati_list_periods
    echo -e "d\tToday"
    echo -e "w\tThis work-week"
    echo -e "m\tThis month"
end

# Disable file completions by default
complete -c yati -f

# Global flags
complete -c yati -l token -d 'Toggl API token'
complete -c yati -l pass-path -d 'Path to token in pass'

# Subcommands (only when no subcommand given yet)
complete -c yati -n __yati_needs_subcommand -a start -d 'Start a new time entry'
complete -c yati -n __yati_needs_subcommand -a stop -d 'Stop the current time entry'
complete -c yati -n __yati_needs_subcommand -a continue -d 'Continue the most recently stopped time entry'
complete -c yati -n __yati_needs_subcommand -a show -d 'Show the current running time entry'
complete -c yati -n __yati_needs_subcommand -a interactive -d 'Start a task interactively'
complete -c yati -n __yati_needs_subcommand -a list -d 'List tasks for a period'
complete -c yati -n __yati_needs_subcommand -a completion -d 'Output shell completion script'

# start flags
complete -c yati -n '__yati_subcommand_is start' -s p -d 'Project ID'

# list period argument
complete -c yati -n '__yati_subcommand_is list' -a '(__yati_list_periods)' -d 'Period'
`

func PrintFishCompletions(w io.Writer) {
	w.Write([]byte(fishCompletions))
}
